//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockLand
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public System.DateTime TradeTime { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Shares { get; set; }
        public string Buyer { get; set; }
        public string Seller { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
